openapi: 3.0.3
info:
  title: OpenApi 3.0
  version: 1.0.11
servers:
  - url: http:/localhost:8080/
tags:
  - name: segment
    description: Operation about segments
    externalDocs:
      description: Find out more
      url: http://swagger.io
  - name: user
    description: Operations about users
paths:
  /add-segment:
    post:
      tags:
        - segment
      summary: Add a new segment to the table
      description: Add a new segment to the table
      operationId: addSegment
      requestBody:
        description: Create a new segment in the table
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Segment'
        required: true
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid input
  /update-segment/{segment_id}:
    put:
      tags:
        - segment
      summary: Update segment
      description: Update info about segment
      operationId: updateSegment
      parameters:
        - name: segment_id
          in: path
          description: name that need to be deleted
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Update info about segment in the table
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Segment'
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid input
  /get-segments:
    get:
      tags:
        - segment
      summary: Get all segments.
      description: Get all segments.
      operationId: GetAllSegments
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Segment'          
        '400':
          description: Invalid tag value
  /delete-segment/{segment_id}:
    delete:
      tags:
        - segment
      summary: Deletes a segment
      description: delete a segment
      operationId: deleteSegment
      parameters:
        - name: segment_id
          in: path
          description: Segment id to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid pet value
  /distribute-segment/{segment_id}:
    post:
      tags:
        - segment
      summary: distribute segment
      description: ''
      operationId: uploadFile
      parameters:
        - name: segment_id
          in: path
          description: Pet id to delete
          required: true
          schema:
            type: integer
            format: int64
        - name: percentage
          in: query
          description: Auto percentage for distribution
          required: false
          schema:
            type: number
            format: float
      responses:
        '200':
          description: successful operation
        '400':
          description: invalid arguments
        '404':
          description: not found
  /get-users:
    get:
      tags:
        - user
      summary: Get users with special segment
      description: 'Get users with special segment'
      operationId: GetUsersWithSegment
      parameters:
        - name: segment_id
          in: query       
          description: ID сегмента для фильтрации пользователей (опционально)
          required: false  
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
        '400':
          description: invalid arguments
  /add-user:
    post:
      tags:
        - user
      summary: Add a new user to the table
      description: Add a new user to the table
      operationId: addUser
      requestBody:
        description: Create a new user in the table
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid input

  /delete-user/{user_id}:
    delete:
      tags:
        - user
      summary: Deletes a user
      description: delete a user
      operationId: deleteUser
      parameters:
        - name: user_id
          in: path
          description: User id to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid pet value
          
  /add-user-to-segment/{user_id}:
    post:
      tags:
        - user
      summary: Add user to segment
      description: 'Add user to segment'
      operationId: Add user to segment
      parameters:
        - name: user_id
          in: path
          description: Add user to segment
          required: true
          schema:
            type: integer
            format: int64
        - name: segment_id
          in: query
          description: segment_id
          required: false
          schema:
            type: number
            format: float
      responses:
        '200':
          description: successful operation
        '400':
          description: invalid arguments
  /delete-user-from-segment/{user_id}:
    delete:
      tags:
        - user
      summary: Delete user from segment
      description: 'Delete user from segment'
      operationId: Delete user from segment
      parameters:
        - name: user_id
          in: path
          description: Delete user from segment
          required: true
          schema:
            type: integer
            format: int64
        - name: segment_id
          in: query
          description: segment_id
          required: false
          schema:
            type: number
            format: float
      responses:
        '200':
          description: successful operation
        '400':
          description: invalid arguments
            
components:
  schemas:
    User:
      type: object
      properties:
        username:
          type: string
          example: Mike
        email:
          type: string
          example: Mike@yandex.ru
    Segment:
      type: object
      properties:
        name:
          type: string
          example: MAIL_VOICE_MESSAGES